/*
  # Seed Demo Content for STREETIZ (v2)

  ## Overview
  Populates the database with realistic demo content including:
  - News articles about clubbing, DJ culture, electronic music
  - Events (DJ sets, battles, festivals)
  - Videos linked to events with geolocation
  - Music tracks and mixes

  Note: Content is created without author_id to avoid foreign key issues
*/

-- Insert News Articles
INSERT INTO news (title, slug, content, excerpt, featured_image, author_id, status, featured, views, published_at) VALUES
(
  'Paris Underground: Inside the T7 Clubbing Revolution',
  'paris-underground-t7-revolution',
  'The Parisian electronic scene has been experiencing a renaissance. T7, located in the heart of the city, has become the epicenter of this movement. With its industrial architecture and cutting-edge sound system, it attracts the world''s top DJs every weekend. The venue''s commitment to underground techno and house music has created a loyal following...',
  'T7 emerges as Paris'' premier destination for underground electronic music with world-class DJs and unmatched atmosphere.',
  'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg',
  NULL,
  'published',
  true,
  15420,
  NOW() - INTERVAL '2 days'
),
(
  'Las Vegas EDM Summit: 50,000 Fans Gather for Epic Festival',
  'las-vegas-edm-summit-festival',
  'The desert transformed into an electronic music paradise as Las Vegas hosted its annual EDM Summit. Over 50,000 fans from around the globe descended upon the festival grounds for three nights of non-stop music. Headliners included Martin Garrix, Carl Cox, and Nina Kraviz. The production featured massive LED screens, pyrotechnics, and a revolutionary 360-degree stage design...',
  'Las Vegas EDM Summit breaks attendance records with 50,000 fans experiencing three nights of electronic music paradise.',
  'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg',
  NULL,
  'published',
  true,
  23890,
  NOW() - INTERVAL '5 days'
),
(
  'World Dance Battle Championship: Tokyo Hosts Elite Breakers',
  'world-dance-battle-championship-tokyo',
  'Tokyo''s Shibuya district became the stage for the most anticipated breaking event of the year. Dancers from 45 countries competed in the World Dance Battle Championship, showcasing incredible athleticism and creativity. The Japanese hosts delivered impeccable organization, and the battles were intense. Red Bull BC One champions faced off against up-and-coming talent in what many called the competition of the decade...',
  'Tokyo hosts 45 countries in the ultimate breaking championship with jaw-dropping performances and unexpected results.',
  'https://images.pexels.com/photos/3775131/pexels-photo-3775131.jpeg',
  NULL,
  'published',
  true,
  18765,
  NOW() - INTERVAL '1 week'
),
(
  'Berlin Techno Scene: Berghain Celebrates 20 Years',
  'berlin-berghain-20-years-anniversary',
  'The legendary Berghain nightclub marks its 20th anniversary this year, cementing its status as the world''s most iconic techno venue. From its strict door policy to its marathon 48-hour sessions, Berghain has defined Berlin''s nightlife culture. Special anniversary events are planned throughout the year, featuring resident DJs and international guests...',
  'Berghain celebrates two decades of defining Berlin''s techno culture and influencing electronic music worldwide.',
  'https://images.pexels.com/photos/2114365/pexels-photo-2114365.jpeg',
  NULL,
  'published',
  false,
  12340,
  NOW() - INTERVAL '3 days'
),
(
  'Amsterdam Dance Event 2024: Record Breaking Edition',
  'amsterdam-dance-event-2024-record',
  'ADE 2024 concluded with record-breaking numbers. Over 400,000 visitors attended events across 200 venues in Amsterdam. The conference portion attracted 3,000 industry professionals discussing the future of electronic music. New technologies like spatial audio and AI-assisted production were hot topics. The festival proved once again why it''s the world''s leading electronic music platform...',
  'Amsterdam Dance Event 2024 sets new records with 400,000 visitors across 200 venues in five-day celebration.',
  'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg',
  NULL,
  'published',
  false,
  9876,
  NOW() - INTERVAL '10 days'
),
(
  'Ibiza Closing Parties: The Season That Never Ends',
  'ibiza-closing-parties-2024-season',
  'As summer draws to a close, Ibiza''s legendary clubs are preparing for their closing parties. Pacha, Amnesia, and Hï Ibiza have announced massive lineups. These events mark the end of another incredible season on the White Isle. Despite rumors of changing regulations, the island continues to be the global capital of dance music...',
  'Ibiza prepares for legendary closing parties marking the end of another unforgettable season on the White Isle.',
  'https://images.pexels.com/photos/1540406/pexels-photo-1540406.jpeg',
  NULL,
  'published',
  false,
  11250,
  NOW() - INTERVAL '4 days'
)
ON CONFLICT (slug) DO NOTHING;

-- Insert Events
INSERT INTO events (title, slug, description, event_date, end_date, location, address, latitude, longitude, featured_image, organizer_id, category, tags, status, ticket_url, price, featured) VALUES
(
  'Afterlife Paris - Tale Of Us',
  'afterlife-paris-tale-of-us',
  'Experience the legendary Afterlife concept in Paris. Tale Of Us brings their unique melodic techno sound to the iconic Zenith venue. Expect a journey through atmospheric soundscapes and hypnotic rhythms. Special stage production and visuals.',
  NOW() + INTERVAL '15 days',
  NOW() + INTERVAL '15 days' + INTERVAL '8 hours',
  'Zenith Paris',
  '211 Avenue Jean Jaurès, 75019 Paris, France',
  48.8937,
  2.3935,
  'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg',
  NULL,
  'party',
  ARRAY['techno', 'melodic', 'afterlife'],
  'published',
  'https://example.com/tickets',
  45,
  true
),
(
  'Red Bull BC One: Berlin Cypher',
  'red-bull-bc-one-berlin-cypher',
  'The world''s best breakers converge on Berlin for the Red Bull BC One Cypher. This qualifying event will determine who advances to the world finals. Expect explosive power moves, intricate footwork, and fierce competition.',
  NOW() + INTERVAL '20 days',
  NOW() + INTERVAL '20 days' + INTERVAL '6 hours',
  'Urban Spree Berlin',
  'Revaler Str. 99, 10245 Berlin, Germany',
  52.5065,
  13.4586,
  'https://images.pexels.com/photos/3775131/pexels-photo-3775131.jpeg',
  NULL,
  'battle',
  ARRAY['breaking', 'battle', 'redbull'],
  'published',
  'https://example.com/tickets',
  0,
  true
),
(
  'Drumcode London: Adam Beyer & Friends',
  'drumcode-london-adam-beyer',
  'Drumcode label boss Adam Beyer brings his signature driving techno sound to London''s legendary Printworks. Joined by label artists for an all-night session of peak-time techno.',
  NOW() + INTERVAL '25 days',
  NOW() + INTERVAL '26 days',
  'Printworks London',
  'Surrey Quays Road, London SE16 7PJ, UK',
  51.4926,
  -0.0520,
  'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg',
  NULL,
  'party',
  ARRAY['techno', 'drumcode', 'industrial'],
  'published',
  'https://example.com/tickets',
  50,
  true
),
(
  'Tomorrowland Winter: Alpine Edition',
  'tomorrowland-winter-alpine',
  'The magic of Tomorrowland meets the Swiss Alps. Three days of electronic music in a breathtaking mountain setting. Multiple stages, world-class DJs, and an unforgettable experience.',
  NOW() + INTERVAL '45 days',
  NOW() + INTERVAL '48 days',
  'Alpe d''Huez',
  'Alpe d''Huez, 38750 France',
  45.0904,
  6.0726,
  'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg',
  NULL,
  'festival',
  ARRAY['festival', 'tomorrowland', 'edm'],
  'published',
  'https://example.com/tickets',
  350,
  true
),
(
  'House Nation: Miami Music Week',
  'house-nation-miami-music-week',
  'Miami Music Week''s hottest party featuring the best in house music. From deep house to tech house, this event showcases the genre''s full spectrum. Beachfront venue with multiple rooms.',
  NOW() + INTERVAL '30 days',
  NOW() + INTERVAL '30 days' + INTERVAL '12 hours',
  'RC Cola Plant Miami',
  '550 NW 24th St, Miami, FL 33127, USA',
  25.7999,
  -80.1977,
  'https://images.pexels.com/photos/1540406/pexels-photo-1540406.jpeg',
  NULL,
  'party',
  ARRAY['house', 'miami', 'mmw'],
  'published',
  'https://example.com/tickets',
  65,
  false
),
(
  'Juste Debout: Hip Hop World Finals',
  'juste-debout-world-finals-paris',
  'The most prestigious hip hop dance competition in the world. Dancers compete in multiple categories: hip hop, house, locking, popping. Held annually in Paris, this event crowns the world champions.',
  NOW() + INTERVAL '35 days',
  NOW() + INTERVAL '35 days' + INTERVAL '10 hours',
  'Bercy Arena Paris',
  '8 Boulevard de Bercy, 75012 Paris, France',
  48.8392,
  2.3790,
  'https://images.pexels.com/photos/3775131/pexels-photo-3775131.jpeg',
  NULL,
  'battle',
  ARRAY['hiphop', 'dance', 'competition'],
  'published',
  'https://example.com/tickets',
  40,
  false
),
(
  'Fabric London: 25th Anniversary',
  'fabric-london-25th-anniversary',
  'London''s legendary Fabric celebrates 25 years of groundbreaking electronic music. Three rooms, multiple generations of ravers, and the finest sound system in the world.',
  NOW() + INTERVAL '40 days',
  NOW() + INTERVAL '41 days',
  'Fabric London',
  '77A Charterhouse St, London EC1M 6HJ, UK',
  51.5201,
  -0.1019,
  'https://images.pexels.com/photos/2114365/pexels-photo-2114365.jpeg',
  NULL,
  'party',
  ARRAY['techno', 'dnb', 'house'],
  'published',
  'https://example.com/tickets',
  35,
  false
),
(
  'Sonar Festival Barcelona',
  'sonar-festival-barcelona-2025',
  'The cutting edge of electronic music and digital culture. Three days and nights of innovation, experimentation, and celebration in Barcelona.',
  NOW() + INTERVAL '60 days',
  NOW() + INTERVAL '63 days',
  'Fira Barcelona',
  'Avinguda de la Reina Maria Cristina, Barcelona, Spain',
  41.3751,
  2.1522,
  'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg',
  NULL,
  'festival',
  ARRAY['electronic', 'experimental', 'sonar'],
  'published',
  'https://example.com/tickets',
  180,
  true
)
ON CONFLICT (slug) DO NOTHING;

-- Insert Videos (linked to events with geolocation)
INSERT INTO videos (title, slug, description, video_url, video_type, thumbnail_url, author_id, category, tags, status, featured, views, duration, city, country, latitude, longitude, year, video_subtype, published_at) VALUES
(
  'Afterlife Paris 2024 - Tale Of Us Complete Set',
  'afterlife-paris-2024-tale-of-us-set',
  'Full recording of Tale Of Us'' mesmerizing performance at Afterlife Paris. Three hours of melodic techno journey.',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg',
  NULL,
  'dj',
  ARRAY['techno', 'melodic', 'paris'],
  'published',
  true,
  45230,
  10800,
  'Paris',
  'France',
  48.8937,
  2.3935,
  2024,
  'DJ Set',
  NOW() - INTERVAL '3 days'
),
(
  'Red Bull BC One Berlin Cypher - Best Moments',
  'red-bull-bc-one-berlin-highlights',
  'The most intense breaking battles from Berlin. Watch world champions clash in this epic compilation.',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  'https://images.pexels.com/photos/3775131/pexels-photo-3775131.jpeg',
  NULL,
  'dance',
  ARRAY['breaking', 'battle', 'berlin'],
  'published',
  true,
  38650,
  1200,
  'Berlin',
  'Germany',
  52.5065,
  13.4586,
  2024,
  'Battle',
  NOW() - INTERVAL '5 days'
),
(
  'Carl Cox - Space Ibiza Closing Party 2024',
  'carl-cox-space-ibiza-closing-2024',
  'The legend himself closes out another incredible Ibiza season. Pure techno energy.',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  'https://images.pexels.com/photos/1540406/pexels-photo-1540406.jpeg',
  NULL,
  'dj',
  ARRAY['techno', 'ibiza', 'closing'],
  'published',
  false,
  29870,
  14400,
  'Ibiza',
  'Spain',
  38.9067,
  1.4206,
  2024,
  'DJ Set',
  NOW() - INTERVAL '7 days'
),
(
  'Tomorrowland 2024 Official Aftermovie',
  'tomorrowland-2024-aftermovie',
  'Relive the magic of Tomorrowland 2024. Three weekends of pure euphoria captured in one epic video.',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg',
  NULL,
  'dj',
  ARRAY['festival', 'tomorrowland', 'edm'],
  'published',
  true,
  125000,
  900,
  'Boom',
  'Belgium',
  51.0933,
  4.3714,
  2024,
  'Aftermovie',
  NOW() - INTERVAL '10 days'
),
(
  'Berghain Raw Session - Anonymous DJ',
  'berghain-raw-session-anonymous',
  'Rare footage from inside Berlin''s most notorious club. Raw, unfiltered techno from the legendary main floor.',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  'https://images.pexels.com/photos/2114365/pexels-photo-2114365.jpeg',
  NULL,
  'dj',
  ARRAY['techno', 'berlin', 'underground'],
  'published',
  false,
  18900,
  7200,
  'Berlin',
  'Germany',
  52.5107,
  13.4427,
  2024,
  'DJ Set',
  NOW() - INTERVAL '12 days'
),
(
  'Juste Debout 2024 - Hip Hop Finals',
  'juste-debout-2024-hiphop-finals',
  'The championship battle that had everyone on their feet. Incredible technique and musicality.',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  'https://images.pexels.com/photos/3775131/pexels-photo-3775131.jpeg',
  NULL,
  'dance',
  ARRAY['hiphop', 'battle', 'finals'],
  'published',
  false,
  22340,
  900,
  'Paris',
  'France',
  48.8392,
  2.3790,
  2024,
  'Battle',
  NOW() - INTERVAL '8 days'
),
(
  'Ultra Miami 2024 - Main Stage Highlights',
  'ultra-miami-2024-mainstage',
  'The biggest moments from Ultra Music Festival Miami. Featuring performances from the world''s top DJs.',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg',
  NULL,
  'dj',
  ARRAY['edm', 'miami', 'festival'],
  'published',
  false,
  67890,
  1800,
  'Miami',
  'United States',
  25.7999,
  -80.1977,
  2024,
  'Aftermovie',
  NOW() - INTERVAL '15 days'
),
(
  'Warehouse Project Manchester - Closing Event',
  'warehouse-project-manchester-closing',
  'The final night of WHP''s season. Absolutely massive crowd and incredible atmosphere.',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg',
  NULL,
  'dj',
  ARRAY['techno', 'manchester', 'warehouse'],
  'published',
  false,
  15670,
  10800,
  'Manchester',
  'United Kingdom',
  53.4808,
  -2.2426,
  2024,
  'DJ Set',
  NOW() - INTERVAL '6 days'
),
(
  'Awakenings Festival Amsterdam 2024',
  'awakenings-festival-amsterdam-2024',
  'Europe''s premier techno festival. Eight stages of pure techno in Amsterdam''s Gashouder venue.',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  'https://images.pexels.com/photos/2114365/pexels-photo-2114365.jpeg',
  NULL,
  'dj',
  ARRAY['techno', 'amsterdam', 'festival'],
  'published',
  true,
  43210,
  3600,
  'Amsterdam',
  'Netherlands',
  52.3676,
  4.9041,
  2024,
  'Aftermovie',
  NOW() - INTERVAL '9 days'
),
(
  'Battle of the Year - Tokyo Qualifiers',
  'boty-tokyo-qualifiers-2024',
  'Crews from across Asia compete for a spot at the Battle of the Year world finals.',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  'https://images.pexels.com/photos/3775131/pexels-photo-3775131.jpeg',
  NULL,
  'dance',
  ARRAY['breaking', 'crew', 'tokyo'],
  'published',
  false,
  19870,
  1800,
  'Tokyo',
  'Japan',
  35.6762,
  139.6503,
  2024,
  'Battle',
  NOW() - INTERVAL '11 days'
)
ON CONFLICT (slug) DO NOTHING;

-- Insert Music Tracks
INSERT INTO music (title, artist, slug, audio_url, cover_image, author_id, genre, tags, duration, status, featured, plays, published_at) VALUES
(
  'Midnight Drive',
  'ARTBAT',
  'midnight-drive-artbat',
  'https://example.com/audio/midnight-drive.mp3',
  'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg',
  NULL,
  'techno',
  ARRAY['melodic', 'progressive'],
  420,
  'published',
  true,
  87650,
  NOW() - INTERVAL '2 days'
),
(
  'Rave Culture',
  'Adam Beyer & Bart Skils',
  'rave-culture-beyer-skils',
  'https://example.com/audio/rave-culture.mp3',
  'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg',
  NULL,
  'techno',
  ARRAY['peak-time', 'driving'],
  360,
  'published',
  true,
  65430,
  NOW() - INTERVAL '4 days'
),
(
  'Solar',
  'Tale Of Us',
  'solar-tale-of-us',
  'https://example.com/audio/solar.mp3',
  'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg',
  NULL,
  'techno',
  ARRAY['melodic', 'afterlife'],
  480,
  'published',
  true,
  92340,
  NOW() - INTERVAL '1 week'
),
(
  'Funk Phenomena',
  'DJ Supreme',
  'funk-phenomena-supreme',
  'https://example.com/audio/funk-phenomena.mp3',
  'https://images.pexels.com/photos/3775131/pexels-photo-3775131.jpeg',
  NULL,
  'breakbeat',
  ARRAY['breaking', 'funk'],
  240,
  'published',
  false,
  34560,
  NOW() - INTERVAL '5 days'
),
(
  'Deep in the Night',
  'Dixon',
  'deep-in-the-night-dixon',
  'https://example.com/audio/deep-night.mp3',
  'https://images.pexels.com/photos/2114365/pexels-photo-2114365.jpeg',
  NULL,
  'house',
  ARRAY['deep-house', 'minimal'],
  540,
  'published',
  false,
  45670,
  NOW() - INTERVAL '3 days'
),
(
  'Energy Flow',
  'Nina Kraviz',
  'energy-flow-nina-kraviz',
  'https://example.com/audio/energy-flow.mp3',
  'https://images.pexels.com/photos/1540406/pexels-photo-1540406.jpeg',
  NULL,
  'techno',
  ARRAY['acid', 'trippy'],
  390,
  'published',
  false,
  56780,
  NOW() - INTERVAL '6 days'
),
(
  'Bassline Dreams',
  'Ben Klock',
  'bassline-dreams-ben-klock',
  'https://example.com/audio/bassline-dreams.mp3',
  'https://images.pexels.com/photos/2114365/pexels-photo-2114365.jpeg',
  NULL,
  'techno',
  ARRAY['berlin', 'industrial'],
  450,
  'published',
  true,
  71230,
  NOW() - INTERVAL '1 day'
),
(
  'Groove Machine',
  'DJ Sneak',
  'groove-machine-dj-sneak',
  'https://example.com/audio/groove-machine.mp3',
  'https://images.pexels.com/photos/1540406/pexels-photo-1540406.jpeg',
  NULL,
  'house',
  ARRAY['chicago', 'groovy'],
  330,
  'published',
  false,
  38900,
  NOW() - INTERVAL '8 days'
)
ON CONFLICT (slug) DO NOTHING;